name: "fastapi-clean-architecture-ddd-template"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APPLICATION_PORT}:8000"
    volumes:
      - ./:/app
    restart: unless-stopped
    container_name: fastapi-clean-architecture-ddd-template
